### ISSUE TITLE
zsh tab completion autoload fails

### ISSUE THREAD

**Issue by majuscule** [evanthegrayt/cdc#4]
not sure what's going on but the autocompletion does not work for me unless I manually run `_cdc_repo_list`, which has resulted in me adding 

```
# workaround for broken cdc autoload
source ~/.antigen/bundles/evanthegrayt/cdc/_cdc.zsh >/dev/null 2>&1
_cdc_repo_list >/dev/null; cd
```

to my .zshrc after `antigen apply`. any ideas why that might be? And even this workaround doesn't seem to work all the time, and I can't figure out why.

super helpful otherwise though, thanks for writing it!

**Comment by majuscule** [comment]
Another odd thing is that when it's not working, it usually pulls up directories like `cd` would, except then can't go to them because it tries to find them in the CDC_DIRS like it should.

**Comment by evanthegrayt** [comment]
🤔 I must have a setting that makes it work for me that's getting loaded by another plugin or something. My brother, who runs on Ubuntu, appears to be having the same issue. Knowing if you're running MacOS or a Linux distro might help me figure it out faster, if you don't mind providing it.

> super helpful otherwise though, thanks for writing it!

Thanks! Glad you're getting use out of it :)

**Comment by evanthegrayt** [comment]
I *may* have fixed this issue? I made a few changes and uninstalled `oh-my-zsh` so I could test with a vanilla install, and it appears to be working. Please pull the changes let me know how it is, if you get a chance! 

If it's still not working, it may be an antigen-specific thing, which I'm not familiar with. I'll look into it if people say it's still broken.

**Comment by astyagun** [comment]
Autocompletions don't work for me with zplugin, no antigen involved

**Comment by tonivj5** [comment]
Any news?

**Comment by evanthegrayt** [comment]
Apologies for the delay, I started a new job and haven't had much time to focus on my personal projects. I believe I may have actually fixed it with [this commit](https://github.com/evanthegrayt/cdc/commit/d0518205af924f6e580aa35a9b42f75928c961ca). Please let me know if it's working. I removed oh-my-zsh for testing and it worked for me. Thanks for your patience!
